/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import quotes.GetQuote;

public class App {
    public static void main(String[] args) {
        GetQuote quote = new GetQuote("app/src/main/resources/recentquotes.json");
        quote.getQuote();
    }
}
